name: todo_reporter_generator
description: A new flutter package project.
version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.6
  todo_reporter:
    path: ../todo_reporter/
  
dev_dependencies:
  build_runner: ^1.10.0